language: node_js
node_js:
  - 10
  - 9
  - 8
cache:
  directories:
    - "$HOME/.npm"
branches:
  only:
    - master
before_install:
  - npm i -g npm@6
install:
  - npm install -g codecov
  - npm ci
script:
  - npm test
  - codecov
